### ISSUE TITLE
Error when running "npm run contributors:add -- username doc"

### ISSUE THREAD

**Issue by lpatmo** [jfmengels/all-contributors-cli#86]
- `all-contributors-cli` version: ^4.11.1
- `node` version: 9.4.0
- `npm` (or `yarn`) version: 5.6.0

What you did:
I ran: `$ npm run contributors:add -- lpatmo doc`

This is after I'd installed the package, and had this in my git diff:
```

lindapeng@Lindas-MacBook-Pro:~/Desktop/lindaprojects/codebuddies$ git diff
diff --git a/package.json b/package.json
index 585505e..c69e7bd 100644
--- a/package.json
+++ b/package.json
@@ -5,7 +5,9 @@
   "scripts": {
     "meteor:dev": "meteor --settings settings-development.json",
     "meteor:prod": "meteor --settings settings-production.json",
-    "test:full-app": "meteor test --full-app --driver-package=practicalmeteor:mocha --settings=settings-development.json --port 3100"
+    "test:full-app": "meteor test --full-app --driver-package=practicalmeteor:mocha --settings=settings-development.json --port 3100",
+    "contributors:add": "all-contributors add",
+    "contributors:generate": "all-contributors generate"
   },
   "dependencies": {
     "babel-runtime": "6.23.0",
@@ -25,6 +27,7 @@
     "uhr": "0.0.2"
   },
   "devDependencies": {
+    "all-contributors-cli": "^4.11.1",
     "cz-conventional-changelog": "2.0.0",
     "faker": "3.1.0"
   },
```

What happened:
The error message:

```$ npm run contributors:add -- lpatmo doc

> codebuddies-v2@1.0.0 contributors:add /Users/lindapeng/Desktop/lindaprojects/codebuddies
> all-contributors add "lpatmo" "doc"

Not Found
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! codebuddies-v2@1.0.0 contributors:add: `all-contributors add "lpatmo" "doc"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the codebuddies-v2@1.0.0 contributors:add script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lindapeng/.npm/_logs/2018-03-19T08_22_20_349Z-debug.log
```

Problem description:
I got the above error after I tried to add a contributor, after installation.

Suggested solution:
Is there a problem using this package with a meteor app?

**Comment by kentcdodds** [comment]
Did you run the `init` command first? That's mentioned in the docs. Perhaps we could handle this error better and init automatically if you haven't already run the `init` command 🤔

**Comment by lpatmo** [comment]
Sorry, I did run `npm init` beforehand, but I forgot to mention it above.

(I assume it is `npm init` and not simply `init`? Because:
```
$ init
-bash: init: command not found
```
)

I just ran `npm init` again, and tried `npm run contributors:add --lpatmo doc`, and the error I see in the log file is:
```
$ cat /Users/lindapeng/.npm/_logs/2018-03-19T20_47_46_134Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/9.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'contributors:add',
1 verbose cli   '--lpatmo',
1 verbose cli   'doc' ]
2 info using npm@5.6.0
3 info using node@v9.4.0
4 verbose run-script [ 'precontributors:add',
4 verbose run-script   'contributors:add',
4 verbose run-script   'postcontributors:add' ]
5 info lifecycle codebuddies@1.0.0~precontributors:add: codebuddies@1.0.0
6 info lifecycle codebuddies@1.0.0~contributors:add: codebuddies@1.0.0
7 verbose lifecycle codebuddies@1.0.0~contributors:add: unsafe-perm in lifecycle true
8 verbose lifecycle codebuddies@1.0.0~contributors:add: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/lindapeng/Desktop/lindaprojects/codebuddies/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle codebuddies@1.0.0~contributors:add: CWD: /Users/lindapeng/Desktop/lindaprojects/codebuddies
10 silly lifecycle codebuddies@1.0.0~contributors:add: Args: [ '-c', 'all-contributors add "doc"' ]
11 silly lifecycle codebuddies@1.0.0~contributors:add: Returned: code: 1  signal: null
12 info lifecycle codebuddies@1.0.0~contributors:add: Failed to exec contributors:add script
13 verbose stack Error: codebuddies@1.0.0 contributors:add: `all-contributors add "doc"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:160:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:160:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid codebuddies@1.0.0
15 verbose cwd /Users/lindapeng/Desktop/lindaprojects/codebuddies
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/Cellar/node/9.4.0/bin/node" "/usr/local/bin/npm" "run" "contributors:add" "--lpatmo" "doc"
18 verbose node v9.4.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error codebuddies@1.0.0 contributors:add: `all-contributors add "doc"`
22 error Exit status 1
23 error Failed at the codebuddies@1.0.0 contributors:add script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]```

**Comment by kentcdodds** [comment]
No, you want to run this:

```javascript
npx all-contributors init
```

Then try everything else.

**Comment by lpatmo** [comment]
Thanks! Closing this issue now. :)

**Comment by lpatmo** [comment]
Oh wait, reopening this issue to report the following: 

```
$ npx all-contributors init
? What's the name of the repository? codebuddies
? Who is the owner of the repository? codebuddies
? What is the repository type? GitHub
? Where is the repository hosted? https://github.com/codebuddiesdotorg/codebuddies
? In which file should contributors be listed? README.md
? Do you want a badge tallying the number of contributors? Yes
? In which file should the badge be shown? README.md
? How big should the avatars be? (in px) 100
? Do you want this badge to auto-commit when contributors are added? Yes

$ npm run contributors:add --lpatmo doc,code

> codebuddies@1.0.0 contributors:add /Users/lindapeng/Desktop/lindaprojects/codebuddies
> all-contributors add "doc,code"

? What are the contribution types? 💬  Answering Questions, 📝  Blogposts, 🐛  Bug reports
Not Found
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! codebuddies@1.0.0 contributors:add: `all-contributors add "doc,code"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the codebuddies@1.0.0 contributors:add script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lindapeng/.npm/_logs/2018-03-19T21_04_44_544Z-debug.log
```

The UI that I saw after running `npx all-contributors init` looked familiar, but I wrote it off. When I ran `npx all-contributors init` a few minutes ago without typing any responses into the prompts and ran `npm run contributors:add --lpatmo doc,code` afterwards, I saw the contributor populate in README.md. But when I tested this a second time and filled in responses, I saw the error above.

**Comment by lpatmo** [comment]
I've filed a new issue at https://github.com/jfmengels/all-contributors-cli/issues/87.
